import Head from "next/head";
import Link from "next/link";
import { Footer } from "@/src/components/Footer";
import { Header } from "@/src/components/Header";
import { Main } from "@/src/components/Main";
import { Typography } from "@/src/components/Typography";
import { useCallback, useEffect } from "react";

export default function Home() {
  const foo = 1;

  const handleClick = useCallback((e) => {
    e.preventDefault();
    alert(foo);
  }, []);

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    }
  }, [])

  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Typography>
        <Link href="/about" onClick={handleClick}>
          ボタン
        </Link>
        <Main page="index" />
        <Footer />
      </Typography>
    </>
  );
}
