import Head from "next/head";
import { Footer } from "@/src/components/Footer";
import { Header } from "@/src/components/Header";
import { Main } from "@/src/components/Main";
import { Typography } from "@/src/components/Typography";
import { useCallback, useEffect, useState } from "react";

export default function Home() {
  const [count, setCount] = useState(1);

  const handleClick = useCallback(() => {
    if (count < 10) {
      setCount(count => count + 1);
    }
  }, [count]);

  useEffect(() => {
    document.body.style.backgroundColor = "lightblue";
    return () => {
      document.body.style.backgroundColor = "";
    }
  }, [])

  return (
    <>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Typography>
        <h1>{count}</h1>
        <button onClick={handleClick}>ボタン</button>
        <Main page="index" />
        <Footer />
      </Typography>
    </>
  );
}
